services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redispass"]

  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "5050:5050"

  gateway:
    build: ./apigateway
    container_name: apigateway
    environment:
      - KEYCLOAK_URL=http://keycloak:5050
    ports:
      - "5000:5000"


  fraud-service:
    build: ./fraud-service
    container_name: fraud-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - KEYCLOAK_URL=http://keycloak:8080
    ports:
      - "5010:5010"
    depends_on:
      - gateway


  ai-score-service:
    build: ./ai-score-service
    container_name: ai-score-service
    ports:
      - "6000:6000"


  rag-service:
    build: ./rag-service
    container_name: rag-service
    ports:
      - "6010:6010"

